### ISSUE TITLE
Plugin doesn't work within macro quasiquote 

### ISSUE THREAD

**Issue by kevinmu** [ghik/silencer#12]
To illustrate the issue I'm running into, I have a simple example:

```
package object mymacro {
  def mac(a: Int): Unit = macro mac_impl

  def mac_impl(c: blackbox.Context)(a: c.Expr[Int]): c.Tree = {
    import c.universe._
    val tree =
      q"""{
         import scala.math.sqrt
         println("TEST MACRO")
       }: @com.github.ghik.silencer.silent
       """
    tree
  }
}
```

In a separate project I call the macro as follows:

```
object Test {
  <path>.<to>.<macro>.<file>.mymacro.mac(0)
}
```

In this example, I expect to silence the `Unused import` warning generated by importing `scala.math.sqrt` and not using it. However, when I compile my project, I still get an `Unused import` warning. Please let me know if I can provide any more details. Thanks!

**Comment by ghik** [comment]
Hello, thanks for the report.
What is the Scala version you're using?

**Comment by kevinmu** [comment]
Hey, I'm using `Scala 2.11.12`, both for the macro and for the project that is using the macro.

**Comment by kevinmu** [comment]
@ghik apologies for the ping, just wondering if there is an update on this issue? thanks!

**Comment by ghik** [comment]
Hello @kevinmu, I'm on vacation this week so I couldn't pick it up, but I will take care of this next week.

**Comment by kevinmu** [comment]
Thanks man, enjoy your vacation!

**Comment by ghik** [comment]
I'm afraid I'll have to declare this wontfix.

In Scala 2.11, macro generated code does not have proper source positions assigned and the plugin cannot tell where the warning is coming from. Additionally, in Scala 2.12 this is no longer an issue because macro-generated code is not linted anyway (https://github.com/scala/scala/pull/5876).

The workaround is to move the `@silent` annotation outside of macro generated code and use it in each macro callsite.

**Comment by kevinmu** [comment]
Ohh ok, I'll try upgrading to Scala 2.12 then. Thanks again for looking into this!
