### ISSUE TITLE
Do not require silencer-lib on classpath

### ISSUE THREAD

**Issue by ashleymercer** [ghik/silencer#23]
Firstly, just wanted to say thanks for this plugin! I found it through [this bug report in Play](https://github.com/playframework/playframework/issues/7382).

When using the plugin as described there, I don't need the `@silent` annotation, since I'm only excluding files based on paths rather than with the annotations - so it's a bit annoying (and ironic :P) that the plugin generates the following warning:

```
[warn] `silencer-plugin` was enabled but the @silent annotation was not found on classpath - have you added `silencer-lib` as a library dependency?
```

Would it be sensible to remove this warning?

**Comment by ghik** [comment]
Right. This warning was introduced when it was only possible to suppress with annotations. I've changed it so that it's emitted only when `globalFilters` and `pathFilters` are empty. I'll do the 1.3.2 release tomorrow.

**Comment by ghik** [comment]
1.3.2 is released.

**Comment by ashleymercer** [comment]
Awesome! Thanks for the quick response :)

**Comment by ashleymercer** [comment]
I've just upgraded to 1.3.3 and I'm still seeing the same issue - would you be able to retest on your side please?

**Comment by ghik** [comment]
I've tested this on a minimal project and it seems to work as intended. Without any options the warning is emitted but when I enable either `messageFilters` or `pathFilters`, the warning disappears. Perhaps some of your subprojects lack these options or have the plugin unnecessarily enabled in the first place (maybe the root project in sbt?).

This warning was originally introduced to avoid build mistakes like [this one](https://github.com/ghik/silencer/issues/5#issuecomment-351852361). If it turns out to be more annoying than helpful then maybe I should remove it again...

**Comment by ashleymercer** [comment]
> perhaps some of your subprojects lack these options

Ahh of course! This is my mistake: I had the compiler plugin enabled on all my subprojects (which all share the same basic configuration) but of course only enabled the filters on some subprojects (e.g. Play modules). You're quite right - it absolutely makes sense to still emit the warning in the "vanilla" case.

Thanks (again) for being so responsive :)
